### ISSUE TITLE
Bug at form validation in edit action - Forms and Actions Tutorial

### ISSUE THREAD

**Issue by RSchilderoth85** [zendframework/tutorials#101]
```php
public function editAction()
    {
        $id = (int) $this->params()->fromRoute('id', 0);

        if (0 === $id) {
            return $this->redirect()->toRoute('album', ['action' => 'add']);
        }

        // Retrieve the album with the specified id. Doing so raises
        // an exception if the album is not found, which should result
        // in redirecting to the landing page.
        try {
            $album = $this->table->getAlbum($id);

        } catch (\Exception $e) {
            return $this->redirect()->toRoute('album', ['action' => 'index']);
        }

        $form = new AlbumForm();
        $form->bind($album);
        $form->get('submit')->setAttribute('value', 'bearbeiten');

        $request = $this->getRequest();
        $viewData = ['id' => $id, 'form' => $form];

        if (! $request->isPost()) {
            return $viewData;
        }

        $form->setInputFilter($album->getInputFilter());
        $form->setData($request->getPost());

        if (! $form->isValid()) {
            return $viewData;
        }

        $this->table->saveAlbum($album);

        // Redirect to album list
        return $this->redirect()->toRoute('album', ['action' => 'index']);
    }
```

This is the code I am using. It is a copy from the "Forms and Actions" - tutorial from here.
https://docs.zendframework.com/tutorials/getting-started/forms-and-actions/ - status from 01.10.2018

If I am going to run this code, I get this error:

![grafik](https://user-images.githubusercontent.com/43743902/46281059-e5a98780-c56d-11e8-88b4-34b92ab2089c.png)

I tried to debug and I know when the problem is raising:

This is the "album" array before 

```
if (! $form->isValid()) {
    return $viewData;
}
```

![grafik](https://user-images.githubusercontent.com/43743902/46281222-58b2fe00-c56e-11e8-838d-315a9dcb28d6.png)

Values are fine, but after the `$form->isValid` function:

![grafik](https://user-images.githubusercontent.com/43743902/46281284-8dbf5080-c56e-11e8-8c2c-46edfc233172.png)

As you can see, the values are now null. I am not sure what exactly the problem is, but I am sure, because of this function -> the values are set to null. When I comment this, everything is working correctly. But I do not have any validation.

I hope for some help.

**Comment by froschdesign** [comment]
@RSchilderoth85 
> This is the "album" array before
`if (! $form->isValid()) { return $viewData; }`

This is not the content of the array. Can you update the last part?

**Comment by RSchilderoth85** [comment]
I hit the enter button too early. But I corrected my post and I hope, it is now understandable.

**Comment by froschdesign** [comment]
Please check the name of the property for the input-filter in your `Album` class. The name looks wrong: `inputfiler`!

**Comment by RSchilderoth85** [comment]
Problems sometimes are so easy to solve ....
Thanks, I did not see this typing error.
