### ISSUE TITLE
How can I use ZFTool for Zend framework 3?.

### ISSUE THREAD

**Issue by jmj4you** [zendframework/tutorials#16]
Hi,
I am new in Zend framework,  let me know how to use ZFtool?. 
I am getting text result while wile I am running zf.php

projectDIR> php  vendor/bin/zf.php

**Comment by weierophinney** [comment]
ZFTool has not been updated to work with v3 at this time. We are planning a rewrite, but have no ETA on when it will be ready.

**Comment by jmj4you** [comment]
Thank you for comment
