### ISSUE TITLE
Error in Getting Started with Zend Framework Database and Models Section

### ISSUE THREAD

**Issue by tomshaw** [zendframework/tutorials#39]
There's no explanation of what the Model\AlbumTableGateway class is.

[Database and Models](https://docs.zendframework.com/tutorials/getting-started/database-and-models/)

```
namespace Album;

// Add these import statements:
use Zend\Db\Adapter\AdapterInterface;
use Zend\Db\ResultSet\ResultSet;
use Zend\Db\TableGateway\TableGateway;
use Zend\ModuleManager\Feature\ConfigProviderInterface;

class Module implements ConfigProviderInterface
{
    // getConfig() method is here

    // Add this method:
    public function getServiceConfig()
    {
        return [
            'factories' => [
                Model\AlbumTable::class => function($container) {
                    $tableGateway = $container->get(Model\AlbumTableGateway::class);
                    return new Model\AlbumTable($tableGateway);
                },
                Model\AlbumTableGateway::class => function ($container) {
                    $dbAdapter = $container->get(AdapterInterface::class);
                    $resultSetPrototype = new ResultSet();
                    $resultSetPrototype->setArrayObjectPrototype(new Model\Album());
                    return new TableGateway('album', $dbAdapter, null, $resultSetPrototype);
                },
            ],
        ];
    }
}
```

**Comment by froschdesign** [comment]
There is a (very) small explanation under the `AlbumTable` code example:

> There's a lot going on here. Firstly, we set the protected property $tableGateway to the TableGateway instance passed in the constructor, hinting against the TableGatewayInterface (which allows us to provide alternate implementations easily, including mock instances during testing). **We will use this to perform operations on the database table for our albums.**

But that is not enough.

**Comment by tomshaw** [comment]
It caught me off guard. Zend Studio has really good error checking. The second you copy code into the editor it lets you know there is a problem. Model\AlbumTableGateway should say Model\Album.
