### ISSUE TITLE
Forms and actions - getArrayCopy

### ISSUE THREAD

**Issue by rogatec** [zendframework/tutorials#43]
The code snippet when [including](https://zendframework.github.io/tutorials/getting-started/forms-and-actions/#form-method) the `InputFilterAwareInterface` to the Album Model show the `getArrayCopy` which is irritating, because at this point of the tutorial it is non existent.

Later when including the hydrator objects it will be implemented. #

**Comment by froschdesign** [comment]
Fixed with #35 

@weierophinney or @ezimuel 
Please close this. Thanks!

**Comment by froschdesign** [comment]
@rogatec 
:+1:
