### ISSUE TITLE
Can't see /album module URL

### ISSUE THREAD

**Issue by user-mw** [zendframework/tutorials#48]
I try to do simple ZF tutorial from here https://docs.zendframework.com/tutorials/getting-started/overview/. I installed ZF 3.0.0. And when I finish this step: https://docs.zendframework.com/tutorials/getting-started/database-and-models/ I can't see /album module in my browser. I do everything according to instructions. But as a result I get "A 404 error occurred Page not found. The requested URL could not be matched by routing." Why? Please help me. I can't understand why I can't do simple tutorial. I use Xammp and Windows 7.

**Comment by divix1988** [comment]
Can you see ZF3 homepage when you access root folder / ? If so then double check your `modules.config.php` that you have: `'Zend\Router'`, also in `module.config.php` check if you have`'router' => [ ... ]` with 'album' key which points at AlbumController, see the code from here: https://docs.zendframework.com/tutorials/getting-started/routing-and-controllers/

**Comment by user-mw** [comment]
I had everything of that according to the instructions. I said had because according to this: https://docs.zendframework.com/tutorials/getting-started/database-and-models/#back-to-the-controller I removed one use-section (and I still can't understand should I have this string: use Zend\Router\Http\Segment; because here https://docs.zendframework.com/tutorials/getting-started/routing-and-controllers/ module.config.php contains that string but with this string or without I have the same bad result) and "entire "controllers" section". Thank you for your help. May be you have any ideas? Have you passed that tutorial success for ZF 3.0.0?

**Comment by adamlundrigan** [comment]
If you're using the latest version of ZendSkeletonApplication you may need to either enable development mode or disable the configuration cache manually ([see this issue for more details](https://github.com/zendframework/ZendSkeletonApplication/issues/368))

**Comment by user-mw** [comment]
"Warning: include(D:\xampp\htdocs\test_zend.local\module\Album\src/config/module.config.php): failed to open stream: No such file or directory in D:\xampp\htdocs\test_zend.local\module\Album\src\Module.php on line 15

Warning: include(): Failed opening 'D:\xampp\htdocs\test_zend.local\module\Album\src/config/module.config.php' for inclusion (include_path='D:\xampp\php\PEAR') in D:\xampp\htdocs\test_zend.local\module\Album\src\Module.php on line 15

Fatal error: Uncaught exception 'Zend\ModuleManager\Listener\Exception\InvalidArgumentException' with message 'Config being merged must be an array, implement the Traversable interface, or be an instance of Zend\Config\Config. boolean given.' in D:\xampp\htdocs\test_zend.local\vendor\zendframework\zend-modulemanager\src\Listener\ConfigListener.php:332 Stack trace: #0 D:\xampp\htdocs\test_zend.local\vendor\zendframework\zend-modulemanager\src\Listener\ConfigListener.php(125): Zend\ModuleManager\Listener\ConfigListener->addConfig('Album', false) #1 D:\xampp\htdocs\test_zend.local\vendor\zendframework\zend-eventmanager\src\EventManager.php(271): Zend\ModuleManager\Listener\ConfigListener->onLoadModule(Object(Zend\ModuleManager\ModuleEvent)) #2 D:\xampp\htdocs\test_zend.local\vendor\zendframework\zend-eventmanager\src\EventManager.php(143): Zend\EventManager\EventManager->triggerListeners(Object(Zend\ModuleManager\ModuleEvent)) #3 D:\xampp\htdocs\test_zend.local\vendor\zendframework\zend-modulemanager\src\ModuleManager.php(18 in D:\xampp\htdocs\test_zend.local\vendor\zendframework\zend-modulemanager\src\Listener\ConfigListener.php on line 332" if I write 'config_cache_enabled' => false, in application.config.php. 

"Fatal error: Class 'ArrayUtils' not found in D:\xampp\htdocs\test_zend.local\public\index.php on line 43" if I enable development mode in GitBash. 
It is so stupid condition I think. The simpliest tutorial and I can't pass it, but I do step by step without any wrong steps. Thank all guys that try to help.  Any ideas?

**Comment by weierophinney** [comment]
> module\Album\src/config/module.config.php

This looks wrong! It appears that your Module is saying the path to configuration is under the `module/Album/src/config/` directory instead of `module/Album/config/`.

Update your `Module::getConfig()` to read:

```
return include '/../config/module.config.php';
```

and you should get rid of that error.

**Comment by user-mw** [comment]
**weierophinney** , you are the Best! Thank you very much! 
Well, I think it will be helpful for the beginners like me:
1. You must have string use Zend\Router\Http\Segment; in your module.config.php that is in your_ZF_dir/module/Album/config (but it isn't written in tutorial, I mean if you didn't notice that string you can miss it).
2. You must write this sting: 'config_cache_enabled' => false, in your_ZF_dir/config/application.config.php (may be enable development mode will help too but I didn't check it).
3. And, the most IMPORTANT advice from **weierophinney**, that in the your_ZF_dir/module/Album/src/Module.php you MUST HAVE THIS getConfig function (instead function in tutorial):
   public function getConfig()
   {
       return include '\..\config\module.config.php';
   }

All other steps according to tutorial.
Thanks again to all users that tried to help me, especially to **weierophinney**.

**Comment by alif-haikal** [comment]
this guys solve the problem .... https://stackoverflow.com/a/55682526/11361114
