### ISSUE TITLE
minor issue in Album-UnitTest-Blog

### ISSUE THREAD

**Issue by bigdocloud** [zendframework/tutorials#49]
Hi Team, 
It is really a great job with regard to ZF3. Much much better organised documents and improved performance. Thanks and congrats!

Some minor issues:
1. In the Module.php of album tutorial:
 return include **DIR** . '/config/module.config.php';
should be:
 return include **DIR** . '/../config/module.config.php';
2. In "Testing actions with POST" of UnitTest, it is not clear about editAction() and deleteAction. "Testing the editAction() and deleteAction() methods can be performed similarly;" To a new babies, we cannot get them. Can you please add detailed function contents?
3. In "writing a factory" of "Blog" tutorial:
return new ListController($container->get(PostRepositoryInterface::class);
should be: return new ListController($container->get(PostRepositoryInterface::class));
1. I wonder if there are some graphs that can concisely illustrate the concepts' relationship and ZF logic structure?
2. Why we need ZF expressive? I couldn't find a tutorial or document from Zend website.

Thanks,

**Comment by bigdocloud** [comment]
2.Why we need ZF expressive? I couldn't find a tutorial or document from Zend website.
--- I meant ZF Expressive-Skeleton. We can add Zend-expressive to MVC skeleton for middleware.

**Comment by adamlundrigan** [comment]
Thanks for your feedback!

> In the Module.php of album tutorial:
> return include DIR . '/config/module.config.php';
> should be:
> return include DIR . '/../config/module.config.php';

There is an open pull request for this typo: https://github.com/zendframework/tutorials/pull/38

This tutorial is intended to be just a little kickstart to point you in the right direction.  The documentation for [`Zend\Test`](http://zendframework.github.io/zend-test/) has slightly more information on the subject.  That module provides some convenience functions for testing controllers, but beyond that you'll be working with pretty standard PHPUnit and Prophecy for which there's good documentation and plenty of tutorials out there. 

If it's something you'd like to see added to the tutorial I would open a separate issue so it's more visible and one of the volunteer documentation writers will consider it. 

> In "writing a factory" of "Blog" tutorial:
> return new ListController($container->get(PostRepositoryInterface::class);
> should be: return new ListController($container->get(PostRepositoryInterface::class));

There is an open pull request for this typo: https://github.com/zendframework/tutorials/pull/31

> I wonder if there are some graphs that can concisely illustrate the concepts' relationship and ZF logic structure?

Not exactly sure what you're thinking of here.  Do you know of an example from another project similar in concept to what you're looking for?  

> Why we need ZF expressive? I couldn't find a tutorial or document from Zend website.
> --- I meant ZF Expressive-Skeleton. We can add Zend-expressive to MVC skeleton for middleware.

Zend Expressive is complimentary to "Zend Framework" (Zend\Mvc, really), like Lumen is to Laravel and Silex is to Symfony.  It implements the [ADR pattern](https://github.com/pmjones/adr) using middleware (Zend\Stratigility) and PSR-7 HTTP messages (Zend\Diactoros).  There's a very good discussion over on the Expressive repository about the difference between the two and when to use each: https://github.com/zendframework/zend-expressive/issues/283

As they are fundamentally different approaches to building applications, each comes with it's own skeleton and tooling.

Expressive and Zend\Mvc cannot be mixed directly, however Zend\Mvc does support dispatching middleware in the same way that Expressive does.  More details on using middleware with Zend\Mvc can be found here: https://docs.zendframework.com/zend-mvc/middleware/

**Comment by bigdocloud** [comment]
Thanks for your reply. 
I got it. Where can I  find a tutorial for expressive skeleton?

Re logic structure and concepts, I meant a graph like a program flow is easier to illustrate the framework flow and concepts relationship. They are already very detailed in the tutorial.

**Comment by adamlundrigan** [comment]
IIRC the tutorial is still a work in progress.  Master Zend Framework has a great introduction to Expressive, [here](http://www.masterzendframework.com/zend-expressive-introduction/).  Ralf Eggert was working on a version of the ZF2 tutorial for Expressive, [here](https://github.com/RalfEggert/zend-expressive-tutorial), but I'm not sure what the status of that is.

**Comment by froschdesign** [comment]
@Haolle 
> 2. In "Testing actions with POST" of UnitTest, it is not clear about editAction() and deleteAction. "Testing the editAction() and deleteAction() methods can be performed similarly;" To a new babies, we cannot get them. Can you please add detailed function contents?

Please open a separate issue for this. Thanks!
