### ISSUE TITLE
Missing example in ZF2 tutorial

### ISSUE THREAD

**Issue by alsuara** [zendframework/tutorials#51]
Dear fiends, perhaps I am mistaken but it seems that in https://framework.zend.com/manual/2.4/en/in-depth-guide/understanding-routing.html there is a sample that I can not see (see the attached image).

![missing-sample](https://cloud.githubusercontent.com/assets/21008901/17643541/24925a1a-616d-11e6-98ab-bfd89b421127.jpg)

I hope being helpful. Best regards.

**Comment by adamlundrigan** [comment]
The version of the document you're referencing is for Zend Framework v2.4, which I believe is still maintained through the [`zf2-documentation`](https://github.com/zendframework/zf2-documentation) repository as 2.4 is still in LTS. (@weierophinney?).  A more up-to-date version of the document can be found here: http://zendframework.github.io/tutorials/in-depth-guide/understanding-routing/

That said, you are correct...there is some issue with the rST document.  The missing example is in the raw source document https://raw.githubusercontent.com/zendframework/zf2-documentation/master/docs/src/in-depth-guide/understanding-routing.rst but isn't appearing in [the rendered output](https://framework.zend.com/manual/2.4/en/in-depth-guide/understanding-routing.html).

**Comment by alsuara** [comment]
Thank you for the detailed answer, Adam.

Great job!
- 
  Alberto Suárez
  http://meucciagency.com
