### ISSUE TITLE
Default [controller_name]/ address doesn't route to index Action

### ISSUE THREAD

**Issue by divix1988** [zendframework/tutorials#52]
I have the following router config:

```
 'users' => [
                'type'    => Segment::class,
                'options' => [
                    'route'    => '/users[/:action][/:id]',
                    'defaults' => [
                        'controller' => Controller\UsersController::class,
                        'action' => 'index',
                    ],
                ],
            ],
```

The URLs like: users/edit points at `editAction()` and users/index calls `indexAction()`.

My main question here is: what's for '**defaults**' key if the address: users/ doesn't point to `indexAction`? Is this a bug or it should work like this, or maybe there is other way to have users/ pointing at index action?

**Comment by adamlundrigan** [comment]
URL routing is intended to be explicit: If you need to respond to `/users` and `/users/` then you should define routes to do that.  This could be accomplished in a number of ways, including modifying the route expression to allow it (as shown in the 3rd link below) or handling it in a web server rewrite rule. 
- http://zend-framework-community.634137.n4.nabble.com/Trailing-slash-tp4655266p4655269.html
- https://framework.zend.com/issues/browse/ZF2-259
- https://samsonasik.wordpress.com/2012/07/24/zend-framework-2-trailing-slash/

**Comment by divix1988** [comment]
@adamlundrigan Sorry I should be more explicit, My problem isn't `/users` and `/users/` but the issue that you need to type `/users/index` in order to go to `indexAction()`, in Zend 1 `/users/` URL pointed by default to index action.

**Comment by adamlundrigan** [comment]
It is true that by default the router does not recognize trailing slashes (see [ZF2-259](https://framework.zend.com/issues/browse/ZF2-259) in the old issue archive).  IIRC it was decided in that ticket that the extra complexity in the regex to make `/users` and `/users/` both translate to `/users/index` was too much for an edge case so users who need it would need to write their own regex ([as samsonasik did](https://samsonasik.wordpress.com/2012/07/24/zend-framework-2-trailing-slash/)) or use a web server rewrite.

My take on it has always been that `/users/index` is a side-effect of the routing process and is not widely used.  The controller index action should have a distinct route and it's `/users`, with both `/users/index` and `/users/` being invalid.  As with any rule, though, there's always an exception: using route parameters with an index action (eg: `/users/index/paramKey/paramValue`), but that's also an edge case holdover from ZF1 IMO.  In ZF2 we intended to push explicit routing defintions over that kind of "magic".
