### ISSUE TITLE
Syntax error in EventManager docs

### ISSUE THREAD

**Issue by divix1988** [zendframework/tutorials#53]
On page: https://docs.zendframework.com/zend-eventmanager/tutorial/ , there is a syntax error:
`$params = )'foo' => 'bar', 'baz' => 'bat'];`
which should be:
`$params = ['foo' => 'bar', 'baz' => 'bat'];`

Has anyone test these examples before publishing?

**Comment by weierophinney** [comment]
> Has anyone test these examples before publishing?

Please have more consideration for the people providing you a _free_ product. I recognize your frustration, but insinuating that those who work on the documentation and/or product are inferior or not diligent discourages contribution.

Finally: please open this on the [zendframework/zend-eventmanager](https://github.com/zendframework/zend-eventmanager) repository, as the relevant documentation is there.

**Comment by divix1988** [comment]
Done and done ;)
