### ISSUE TITLE
Undefined index db in ZF3 tutorial

### ISSUE THREAD

**Issue by DragonBe** [zendframework/tutorials#56]
Following the instructions on [Getting started: A skeleton application](https://docs.zendframework.com/tutorials/getting-started/skeleton-application/) including all modules during installation, I get the following error when going to the app locally using Apache or the build-in php web server:

```
Notice: Undefined index: db in /var/www/zf3-tutorial/vendor/zendframework/zend-db/src/Adapter/AdapterServiceFactory.php on line 27

Fatal error: Uncaught Zend\Db\Adapter\Exception\InvalidArgumentException: The supplied or instantiated driver object does not implement Zend\Db\Adapter\Driver\DriverInterface in /var/www/zf3-tutorial/vendor/zendframework/zend-db/src/Adapter/Adapter.php:82 Stack trace: 
#0 /var/www/zf3-tutorial/vendor/zendframework/zend-db/src/Adapter/AdapterServiceFactory.php(27): Zend\Db\Adapter\Adapter->__construct(NULL) 
#1 /var/www/zf3-tutorial/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(750): Zend\Db\Adapter\AdapterServiceFactory->__invoke(Object(Zend\ServiceManager\ServiceManager), 'Zend\\Db\\Adapter...', NULL) 
#2 /var/www/zf3-tutorial/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(198): Zend\ServiceManager\ServiceManager->doCreate('Zend\\Db\\Adapter...') 
#3 /var/www/zf3-tutorial/vendor/zendframework/zend-developer-tools/src/Module.php(204): Zend\ServiceManager\ServiceMa in /var/www/zf3-tutorial/vendor/zendframework/zend-servicemanager/src/ServiceManager.php on line 757
```

The configuration for the database is only 2 pages further in [Database and models - Using ServiceManager to configure the table gateway and inject into the AlbumTable](https://docs.zendframework.com/tutorials/getting-started/database-and-models/#using-servicemanager-to-configure-the-table-gateway-and-inject-into-the-albumtable).

Maybe it would be good to add in the  [Getting started: A skeleton application](https://docs.zendframework.com/tutorials/getting-started/skeleton-application/) a minimal db configuration example like the following:

``` php
// file: config/autoload/global.config
return [
        'driver' => 'Pdo',
        'dsn' => 'sqlite::memory:',
];
```

This small addition will allow new users to at least see the ZF example page without errors if they install all modules, including `zend-db`.

[![zf3_demo_page](https://cloud.githubusercontent.com/assets/282825/18268789/9e56e440-7425-11e6-8ee8-bf6e5e634626.png)](https://cloud.githubusercontent.com/assets/282825/18268789/9e56e440-7425-11e6-8ee8-bf6e5e634626.png)

On page [Database and models - Using ServiceManager to configure the table gateway and inject into the AlbumTable](https://docs.zendframework.com/tutorials/getting-started/database-and-models/#using-servicemanager-to-configure-the-table-gateway-and-inject-into-the-albumtable) mention can be made to replace the existing `db` configuration with the example configuration.

**Comment by weierophinney** [comment]
@DragonBe would you be willing to provide a PR with the requested changes? They make sense to me.

**Comment by weierophinney** [comment]
Never mind, just found #57, @DragonBe — thanks!

**Comment by DragonBe** [comment]
You're welcome ;-)

**Comment by samsonasik** [comment]
should be fixed by https://github.com/zendframework/ZendDeveloperTools/pull/218 , close-able

**Comment by froschdesign** [comment]
Closing (see also #57)
