### ISSUE TITLE
Wrong Module::getConfig() path

### ISSUE THREAD

**Issue by MaximumP** [zendframework/tutorials#58]
At least at my ubuntu 16.04 system. The wrong path for the module.config.php is provided.

At https://docs.zendframework.com/tutorials/getting-started/modules/  -> Setting up the Album module

``` php
    public function getConfig()
    {
        return include __DIR__ . '/config/module.config.php';
    }
```

for me it had to be

``` php
    public function getConfig()
    {
        return include __DIR__ . '/../config/module.config.php';
    }
```

**Comment by weierophinney** [comment]
Fixed with #38
