### ISSUE TITLE
$container->get(AdapterInterface::class)

### ISSUE THREAD

**Issue by rajeshpatel1993** [zendframework/tutorials#61]
$container->get(AdapterInterface::class) is returning none in factory,
where it is configured in module.config.php

**Comment by froschdesign** [comment]
Which tutorial do you mean? "**Getting Started with Zend Framework**" or "**In-Depth tutorial**"?

In the "**Getting Started**" tutorial you will find these lines:

> The Zend\Db\Adapter\AdapterInterface service is registered by the zend-db component. You may have noticed earlier that config/modules.config.php contains the following entries:

https://docs.zendframework.com/tutorials/getting-started/database-and-models/#using-servicemanager-to-configure-the-table-gateway-and-inject-into-the-albumtable

In the "**In-Depth tutorial**" you will find this hint:

> #### Preparing the Database
> 
> This tutorial assumes you've followed the Getting Started tutorial, and that you've already populated the data/zftutorial.db SQLite database. We will be re-using it, and adding another table to it.

https://docs.zendframework.com/tutorials/in-depth-guide/zend-db-sql-zend-hydrator/#preparing-the-database

(Btw. there is an [own tutorial](https://docs.zendframework.com/tutorials/db-adapter/) to setting up a database adapter)

**Comment by froschdesign** [comment]
@weierophinney 
Can we close this?
