### ISSUE TITLE
Zend Framework 3 issue getConfig() function not call automatically in Application Module

### ISSUE THREAD

**Issue by ajaybadhe** [zendframework/tutorials#63]
getConfig() not call automatically in Application Module

**Comment by weierophinney** [comment]
Please provide more details on how to reproduce the issue.

At this time, I cannot recreate the problem; the method is called whenever the application runs, as part of module initialization.

**Comment by ajaybadhe** [comment]
Problem Solved.

**Comment by jasonterando** [comment]
@ajaybadhe - I ran into the same issue with ZF3 skeleton, how did you resolve this?  Thanks!
