### ISSUE TITLE
Zend Framework 3: Autoload Custom Libraries

### ISSUE THREAD

**Issue by JitenSabharwal** [zendframework/tutorials#65]
Can any one tell how to include the Custom Libraries in Zend Framework 3 .
I have tried implementing the way that was used for Zend Framework 2 but I'm still getting this error

Fatal error: Class 'Lib\FusionCharts' not found in /var/www/html/skeleton/module/Album/src/Controller/AlbumController.php on line 13

I have created a folder Lib in the vendor forlder of the zend framework which has my custom Class FusionCharts which I want to include in index page of the "album"

![error](https://cloud.githubusercontent.com/assets/6931830/20518858/b3ee32f8-b0c6-11e6-888e-ff2c227328f3.png)
![module](https://cloud.githubusercontent.com/assets/6931830/20518877/c302aee0-b0c6-11e6-9e3d-ff6833c57c78.png)
![albumcontroller](https://cloud.githubusercontent.com/assets/6931830/20518894/d5e8b6c6-b0c6-11e6-9216-30cf4d6b25f4.png)

**Comment by froschdesign** [comment]
Sorry for the late response.

> I have created a folder Lib in the vendor folder…

Never edit or touch the "vendor" folder. Use the composer instead: "[Repositories - Hosting your own](https://getcomposer.org/doc/05-repositories.md#hosting-your-own)"
