### ISSUE TITLE
Misinformation in tutorial

### ISSUE THREAD

**Issue by chenchotshering** [zendframework/tutorials#66]
Dear ZF2 Team,
I am learning Zf2 for first time but i think i spotted some improper documentation on the Zf2. Please visit following link to get you to error.

1. https://framework.zend.com/manual/2.3/en/getting-started-with-zend-studio/the-application.html

This link has mistake on routing under The application's Page.  It was given that the routing link is module/Checklist/src/config/module.config.php but i believe /config/module.config.php should be under module/Checklist/ not under /src/ please check properly. 

2.    https://framework.zend.com/manual/2.3/en/in-depth-guide/data-binding.html

Under Creating the edit template the name for edit action is missing the file name is given with add action i.e   It should be edit.phtml. 

The problem looks very simple but for person who is learning first time it is really headache. Please don't mind if i made a mistake on informing this issue. 

Thanks

**Comment by froschdesign** [comment]
@chenchotshering 
These documentations are outdated. Please use [docs.zendframework.com](https://docs.zendframework.com/tutorials/)
