### ISSUE TITLE
Trouble with Tutorial on Zend 2 (myabums project), Application Module could not be initialized

### ISSUE THREAD

**Issue by mhsaufi** [zendframework/tutorials#69]
Fatal error: Uncaught exception 'Zend\ModuleManager\Exception\RuntimeException' with message 'Module (Application) could not be initialized.' in C:\xampp\htdocs\myalbums\vendor\zendframework\zend-modulemanager\src\ModuleManager.php:203 Stack trace: #0 C:\xampp\htdocs\myalbums\vendor\zendframework\zend-modulemanager\src\ModuleManager.php(175): Zend\ModuleManager\ModuleManager->loadModuleByName(Object(Zend\ModuleManager\ModuleEvent)) #1 C:\xampp\htdocs\myalbums\vendor\zendframework\zend-modulemanager\src\ModuleManager.php(97): Zend\ModuleManager\ModuleManager->loadModule('Application') #2 C:\xampp\htdocs\myalbums\vendor\zendframework\zend-eventmanager\src\EventManager.php(322): Zend\ModuleManager\ModuleManager->onLoadModules(Object(Zend\ModuleManager\ModuleEvent)) #3 C:\xampp\htdocs\myalbums\vendor\zendframework\zend-eventmanager\src\EventManager.php(171): Zend\EventManager\EventManager->triggerListeners(Object(Zend\ModuleManager\ModuleEvent)) #4 C:\xampp\htdocs\myalbums\vendor\zendframework\zend-modulemanager\src\ModuleMan in C:\xampp\htdocs\myalbums\vendor\zendframework\zend-modulemanager\src\ModuleManager.php on line 203

i had follow thoroughly all the tutorial guide because i am totally new to zend 2 framework but when i reach the step where i add Album modules in Albums/config/autoload/application.config.php, i refresh http://myalbums, then i get this error. What had went wrong? Anyone had exerience this, i may need your help here, thank you.

**Comment by weierophinney** [comment]
Which tutorial are you following, exactly? How have you created your initial application?

**Comment by mhsaufi** [comment]
This tutorial,
https://www.youtube.com/watch?v=jxW2ES52_-E

on 6:55 , right when he refresh it, he got a problem too, but he fix it. But mine isnt the same as he is.

**Comment by weierophinney** [comment]
That tutorial was not produced by Zend or by a community contributor, so I cannot troubleshoot for you at this time.

You may follow our official tutorials from our own [documentation site](https://docs.zendframework.com/tutorials/), and, if you have further questions or run into errors, open new issues or pull requests.
