### ISSUE TITLE
Installing zend 2 installs zend 3

### ISSUE THREAD

**Issue by darius-v** [zendframework/tutorials#72]
Look at this. I had also same problem, now trying as in answer.

http://stackoverflow.com/questions/41911128/how-to-install-zend-framework-2-4-11-skeleton-application

Installing as in answer worked, at least now I see Zend 2 starting page when I run.

**Comment by froschdesign** [comment]
Run:

```bash
composer create-project zendframework/skeleton-application:^2.4.11
```

But you should use ZF3. Is the same like version 2 but cleaned up. (Also worth a look is [`zend-expressive`](https://docs.zendframework.com/zend-expressive/).)

**Comment by darius-v** [comment]
I tried to use ZF3 but there is not enough info in documentation. I tried few times to use dependency injection, but was not able to. I would prefer to wait till there is more info on it.

When I open ZF3 DI page, there is the link to packagist for instalation and thats it.

https://docs.zendframework.com/zend-di/

When I enter into google zend 3 dependency injection I get zend 2 di page and did not even notice in first 10 links info about zend 3 DI.

Its very big productivity killer when you cant find info.

**Comment by froschdesign** [comment]
> When I open ZF3 DI page, there is the link to packagist for instalation and thats it.

Please look at the top navigation bar, there you can find all the links for the documentation.

> Its very big productivity killer when you cant find info.

`zend-di` is not the recommended way. Have a look at the [`zend-servicemanager`](https://docs.zendframework.com/zend-servicemanager/).
