### ISSUE TITLE
 Uncaught exception 'Zend\ModuleManager\Exception\RuntimeException' with message 'Module (Album) could not be initialized.

### ISSUE THREAD

**Issue by azy12** [zendframework/tutorials#73]
I've been following [this tutorial](https://docs.zendframework.com/tutorials/getting-started/overview/) up to [here](https://docs.zendframework.com/tutorials/getting-started/database-and-models/) but when i run what i see in my browser is the code inside /module/Album/src/Module.php and also the message saying Module(Album) could not be initialized. What could've been wrong? 
-Also, when I enable development mode I cannot open the ZF homepage, I got this:

> Fatal error: Class 'ArrayUtils' not found in /var/www/ZendSkeletonApplication/public/index.php on line 43

**Comment by froschdesign** [comment]
> i see in my browser is the code inside /module/Album/src/Module.php

Please look at the `Module.php`file and recheck if the PHP open tag is present:

```php
<?php

namespace Album;

// …

**Comment by azy12** [comment]
I've added the PHP open tag. Now I'm getting this

> Fatal error: Uncaught exception 'Zend\ModuleManager\Listener\Exception\InvalidArgumentException' with message 'Config being merged must be an array, implement the Traversable interface, or be an instance of Zend\Config\Config

**Comment by froschdesign** [comment]
I think, the last part of the error message is missing. Can you provide the whole message? There we can find the type of your current config.

**Comment by azy12** [comment]
![img_20170220_224451](https://cloud.githubusercontent.com/assets/25496180/23130074/09653aac-f7c0-11e6-9d97-4d855f1ff97b.JPG)

**Comment by froschdesign** [comment]
Please fix the error: the `module.config.php` can't be found. 

In the tutorial you find the explanation for the this file: https://docs.zendframework.com/tutorials/getting-started/modules/#configuration

**Comment by froschdesign** [comment]
@weierophinney 
Can we close this!

**Comment by innovasistemas** [comment]
Hi. Continuous fix

**Comment by subratpalhar92** [comment]
Hi,, the problem still persist, Even after i have followed & double checked the above procedure.

**Comment by Ocramius** [comment]
@subratpalhar92 open a new issue with a clear stack trace, please.
