### ISSUE TITLE
de/learning.quickstart.create-model SQL issue

### ISSUE THREAD

**Issue by C4landra** [zendframework/tutorials#85]
[https://framework.zend.com/manual/1.11/de/learning.quickstart.create-model.html](url)

Just found that the german Translation has an issue in one of the SQL Statements: 

-- scripts/data.sqlite.sql
-- Man kann damit beginnen die Datenbank zu befüllen indem die folgenden SQL
-- Anweisungen ausgeführt werden.
 
INSERT INTO guestbook (email, comment, created) VALUES
    ('ralph.schindler@zend.com',
    'Hallo! Hoffentlich geniesst Ihr dieses Beispiel einer ZF Anwendung!
    DATETIME('NOW'));
INSERT INTO guestbook (email, comment, created) VALUES
    ('foo@bar.com',
    'Baz baz baz, baz baz Baz baz baz - baz baz baz.',
    DATETIME('NOW'));

should be:

-- Man kann damit beginnen die Datenbank zu befüllen indem die folgenden SQL
-- Anweisungen ausgeführt werden.
 
INSERT INTO guestbook (email, comment, created) VALUES
    ('ralph.schindler@zend.com',
    'Hallo! Hoffentlich geniesst Ihr dieses Beispiel einer ZF Anwendung!',
    DATETIME('NOW'));
INSERT INTO guestbook (email, comment, created) VALUES
    ('foo@bar.com',
    'Baz baz baz, baz baz Baz baz baz - baz baz baz.',
    DATETIME('NOW'));

so an ', is missing in line 8.

**Comment by froschdesign** [comment]
@C4landra 
We are sorry, but [ZF1 reaches its End of Life (EOL)](https://framework.zend.com/blog/2016-06-28-zf1-eol.html).
You should use version 2 and 3. [zend-expressive](https://docs.zendframework.com/zend-expressive/) is a very good start for new applications.

(By the way, this is the wrong issue tracker for ZF1. See: https://github.com/zendframework/zf1/issues)
