### ISSUE TITLE
css on website - tutorial page

### ISSUE THREAD

**Issue by tasmaniski** [zendframework/tutorials#92]
Not sure if this is a right repo. to open issue? 

As you can see from the image, text is hardly visible.
This problem occurs only on tutorial page. 
![ss](https://user-images.githubusercontent.com/2909695/33850904-a7703e04-deb5-11e7-9f80-a3e2ebeca753.png)

I am using Ubuntu and Chrome.

**Comment by froschdesign** [comment]
@tasmaniski 
> As you can see from the image, text is hardly visible.

Sorry at the moment I can not found a problem in CSS. The link color is correct.
We working on a [new layout](https://github.com/zendframework/zf-mkdoc-theme/pull/34) which includes also many updates for CSS. I hope we can fix the font color problem with this update.

Thanks for reporting!

**Comment by michalbundyra** [comment]
@tasmaniski @froschdesign 
I've checked on Ubuntu (16.04) and Chrome (Version 63.0.3239.84 (Official Build) (64-bit)), and it looks like on screenshot below:
![image](https://user-images.githubusercontent.com/7423207/33872492-09abadde-df0f-11e7-895d-62e47ccc1e63.png)

@tasmaniski maybe you are using some extension which modify styles? Try incognito mode.

**Comment by froschdesign** [comment]
@webimpress 
Great! Thanks for testing.

**Comment by tasmaniski** [comment]
I am using Chrome Version 56.0.2924.87 (64-bit) and Ubuntu 14.04 LTS. 
But this happen on the Firefox too. 

If you are preparing new layout don't worry about this.

**Comment by michalbundyra** [comment]
@tasmaniski I've checked the page also using http://browsershots.org/https://docs.zendframework.com/tutorials/
and I can't see anywhere that grey text colour.

**Comment by froschdesign** [comment]
@webimpress 
The font is too thin, this results in rendering problems.

Example: http://api.browsershots.org/png/original/be/be98792173213445a44071912a178bd8.png

**Comment by michalbundyra** [comment]
@froschdesign Yes, saw it, but the colour is still blue, and on original screenshot from the issue it looks more like grey.
Anyway, we can test new layout with this tool once you finish fixes :smile:
