### ISSUE TITLE
Module (Album) could not be initialized

### ISSUE THREAD

**Issue by mohammedali1140220** [zendframework/tutorials#95]
I have this Fatal error when i follow the Zend Framework 2 official tutorial, i reach here : https://framework.zend.com/manual/2.4/en/user-guide/database-and-models.html

When i follow each step i have this error : 
Fatal error: Uncaught Zend\ModuleManager\Exception\RuntimeException: Module (Album) could not be initialized. in C:\xampp\htdocs\zf2\vendor\zendframework\zend-modulemanager\src\ModuleManager.php:203 Stack trace: #0 C:\xampp\htdocs\zf2\vendor\zendframework\zend-modulemanager\src\ModuleManager.php(175): Zend\ModuleManager\ModuleManager->loadModuleByName(Object(Zend\ModuleManager\ModuleEvent)) #1 C:\xampp\htdocs\zf2\vendor\zendframework\zend-modulemanager\src\ModuleManager.php(97): Zend\ModuleManager\ModuleManager->loadModule('Album') #2 [internal function]: Zend\ModuleManager\ModuleManager->onLoadModules(Object(Zend\ModuleManager\ModuleEvent)) #3 C:\xampp\htdocs\zf2\vendor\zendframework\zend-eventmanager\src\EventManager.php(490): call_user_func(Array, Object(Zend\ModuleManager\ModuleEvent)) #4 C:\xampp\htdocs\zf2\vendor\zendframework\zend-eventmanager\src\EventManager.php(248): Zend\EventManager\EventManager->triggerListeners('loadModules', Object(Zend\ModuleManager\ModuleEvent)) #5 C:\xampp\htdocs\zf2\vendor\zendframework in C:\xampp\htdocs\zf2\vendor\zendframework\zend-modulemanager\src\ModuleManager.php on line 203

anyone can help ?

**Comment by froschdesign** [comment]
@mohammedali1140220 
> when i follow the Zend Framework 2 official tutorial

This is the old version of the tutorial. (See at the top of the tutorial page.)
Here you can find the current version: https://docs.zendframework.com/tutorials/

> Module (Album) could not be initialized.

Please post your `Module.php` here. The file / class seems to be wrong.

**Comment by vrkansagara** [comment]
@mohammedali1140220  here is reference for the `Album` module https://github.com/vrkansagara/album

**Comment by froschdesign** [comment]
@vrkansagara 
You use also the old version of the tutorial.
`Album\Module\getAutoloaderConfig()` can be removed. Use Composer instead.

See: https://docs.zendframework.com/tutorials/getting-started/modules/#autoloading

In the newer versions of zend-mvc this will not work: https://github.com/vrkansagara/album/blob/master/src/Album/Controller/AlbumController.php#L144

**Comment by vrkansagara** [comment]
@froschdesign  You are right. As I have already mentioned that `This module support zendframework/zendframework": "~2.4.11` [here](https://github.com/vrkansagara/album)

**Comment by froschdesign** [comment]
@vrkansagara 
And this repository is for https://docs.zendframework.com/tutorials/  (>2.4) :wink:

**Comment by froschdesign** [comment]
Closing due inactivity.
